sylius_twig_hooks:
    hooks:
        'sylius_admin.base#javascripts':
            payment_fee_javascripts:
                template: '@ThreeBRSSyliusPaymentFeePlugin/Admin/_javascripts.html.twig'
                priority: 10