services:
    app:
        build: .
        hostname: app.docker
        container_name: sylius-payment-fee-plugin-app
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Prague"
            COMPOSER_HOME: "/tmp"
            YARN_CACHE_FOLDER: "/tmp"
            HOME: "/tmp"
            XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003 remote_log=/tmp/xdebug.log"
            XDEBUG_TRIGGER: "yes" # to start XDebug for EVERY request (use `export XDEBUG_TRIGGER: "yes"` to enable it in CLI and `unset XDEBUG_TRIGGER` to disable for CLI again - in browser use same-named variable in GET, POST or COOKIE, or legacy XDEBUG_SESSION via some browser extension). For a single shot can be used inline environment variable like `XDEBUG_TRIGGER=yes ./bin/console
            #            XDEBUG_MODE: "off"
            XDEBUG_MODE: "debug"
            #            XDEBUG_MODE: "profile"
            XDEBUG_MODE_BEHAT: "off"
            PHP_IDE_CONFIG: "serverName=3brsSyliusPaymentFeePlugin"
            BEHAT_PARAMS: '{"extensions":{"Behat\\MinkExtension":{"base_url":"https://app.docker:8081/","sessions":{"chrome_headless":{"chrome":{"api_url":"http://chrome.docker:9222"}}}}}}'
        volumes:
            - ./:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
#            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - "${APP_HOST_MAPPING_PORT:-8080}:443" # http://localhost:8080
            - "${APP_HOST_MAPPING_PORT:-8081}:8081" # http://localhost:8081
        depends_on:
            - mysql
#            - postgres
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        container_name: sylius-payment-fee-plugin-mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            # Host port 0 is for "first available"
            # How to change it:
            # - set MYSQL_HOST_MAPPING_PORT variable in .env file for example
            # - or extends ports in docker-compose.override.yml
            # To find out used port use `docker ps` and look for PORTS column to see mapped host port, including IP it can be for example 0.0.0.0:32772 which is roughly equivalent to 127.0.0.1:32772 for internal network requests
            - "${MYSQL_HOST_MAPPING_PORT:-32772}:3306"
        networks:
            - sylius

#    postgres:
#        image: postgres:14-alpine
#        container_name: sylius-payment-fee-plugin-postgres
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - ${POSTGRES_PORT:-5432}:5432
#        networks:
#            - sylius

    chrome.docker:
        # Thank you https://pplotka.dev/post/sylius-behat-scenarios-in-chrome-headless-inside-docker/
        image: zenika/alpine-chrome
        container_name: sylius-payment-fee-plugin-chrome
        shm_size: "2gb"
        command: "--enable-automation --disable-gpu --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --disable-translate --disable-extensions --no-sandbox --headless --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' --disable-proxy-certificate-handler"
        networks:
            - sylius


networks:
    sylius:
        driver: bridge
