sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.update.content.form.sections':
            3brs_payment_fee:
                template: '@ThreeBRSSyliusPaymentFeePlugin/Admin/_form.html.twig'
                priority: 50
