sylius_twig_hooks:
    hooks:
        'sylius_shop.shared.order.show.summary.table_summary':
            payment_fee:
                template: '@ThreeBRSSyliusPaymentFeePlugin/Shop/shared/order/show/summary/table_summary/payment_fee.html.twig'
                priority: 150
        'sylius_shop.shared.order.show.summary.table_summary.payment_fee':
            label:
                template: '@ThreeBRSSyliusPaymentFeePlugin/Shop/shared/order/show/summary/table_summary/payment_fee/label.html.twig'
                priority: 100
            value:
                template: '@ThreeBRSSyliusPaymentFeePlugin/Shop/shared/order/show/summary/table_summary/payment_fee/value.html.twig'
                priority: 0
